{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-testing",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-testing-2.6.1.aar",
          "url": "room-testing-2.6.1.aar",
          "size": 23435,
          "sha512": "462c493f7e2d17af3600befb1e946b2857e454bbca96405fd60577829f15a3c5b66a81eb0dec799620cab2e135f0cc3d6494ae884d186f10335b2032ab17bf10",
          "sha256": "ea66d01428a8c8f26a0ee2259a96d7763dd0d3aef5321730790f8e9cfbe28360",
          "sha1": "d514ccdeb4fd9770e3a36f7dc2f2a425cb9bbbfb",
          "md5": "01eb4dee98f5e359d217923f1e2cb4fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-testing-2.6.1.aar",
          "url": "room-testing-2.6.1.aar",
          "size": 23435,
          "sha512": "462c493f7e2d17af3600befb1e946b2857e454bbca96405fd60577829f15a3c5b66a81eb0dec799620cab2e135f0cc3d6494ae884d186f10335b2032ab17bf10",
          "sha256": "ea66d01428a8c8f26a0ee2259a96d7763dd0d3aef5321730790f8e9cfbe28360",
          "sha1": "d514ccdeb4fd9770e3a36f7dc2f2a425cb9bbbfb",
          "md5": "01eb4dee98f5e359d217923f1e2cb4fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-testing-2.6.1-sources.jar",
          "url": "room-testing-2.6.1-sources.jar",
          "size": 7054,
          "sha512": "8c34729471e0899d7feebd036551f57c9d18ed4b5ea0a9679c1f678e7c9fe2fe7dba02a1cb1b2440c35c86ebd942135190d14430d912642ce890ef92355ff992",
          "sha256": "e9c6087f3564e7eb41c21c15d00a5a2df6530203486cc672656638e215ff04ca",
          "sha1": "a1ac7145802058a30cd86461af2ec1b5af11f2da",
          "md5": "6e87c7d4130d7c6173ad784f2ebe5475"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "room-testing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-testing-2.6.1-versionMetadata.json",
          "url": "room-testing-2.6.1-versionMetadata.json",
          "size": 1911,
          "sha512": "a375e9e8ef389bec0af1023b3e0ab1be160d992b9ce5a4594e48bfb442725cf51feb834f9b895035e26de5deef9e89ab41ef881df28d2c0911fb2e3bdc827899",
          "sha256": "c61d3ce4a63c0a26c1c8e0d991f76562541d2bf5c821cb739e8dd3e22f51b56a",
          "sha1": "518c5515d39c19837f15b04c32202e529fdae799",
          "md5": "2b0fb496a1d1aaa4e051968aa40847e0"
        }
      ]
    }
  ]
}